services:

    # nginx

     web:
       
        image: nginx:latest

        ports:
      
            - "8080:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./app/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

    # php
     app:

        build:

              dockerfile: ./php/Dockerfile
              target: "${BUILD_TARGET:-app}"
        volumes:
            - ./app:/var/www/html
        environment:
            MYSQL_HOST: db
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            REDIS_HOST: cache
            REDIS_PORT: ${REDIS_PORT}
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
        extra_hosts:
            - host.docker.internal:host-gateway
    # mysql
     db:
        image: mysql:8.0

        volumes:
            - mysqldata:/var/lib/mysql

        ports:
            - "4306:3306"

        restart: unless-stopped

        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: docker-php

    # redis
    
     cache:
         image: redis:latest

volumes:
    mysqldata:
